# Generated by Django 3.2.17 on 2023-02-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.TextField()),
                ('telefono_proveedor', models.TextField()),
                ('direccion_proveedor', models.TextField()),
                ('cif_proveedor', models.TextField()),
                ('facturacion_proveedor', models.FloatField()),
            ],
        ),
    ]
