# Generated by Django 3.2.17 on 2023-02-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorEmpresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_producto', models.TextField()),
                ('descripcion_producto', models.TextField()),
                ('almacen_producto', models.TextField()),
                ('precio_producto', models.FloatField()),
                ('stockMax_producto', models.IntegerField()),
                ('stockActual_producto', models.IntegerField()),
                ('proveedor_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorEmpresa.proveedores')),
            ],
        ),
    ]
