# Generated by Django 3.2.17 on 2023-02-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorEmpresa', '0002_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
        migrations.RenameModel(
            old_name='Proveedores',
            new_name='Proveedor',
        ),
    ]
