# Generated by Django 3.2.17 on 2023-02-03 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorEmpresa', '0003_auto_20230203_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.TextField()),
                ('telefono_cliente', models.TextField()),
                ('direccion_cliente', models.TextField()),
                ('cif_cliente', models.TextField()),
                ('gasto_cliente', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento_producto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='iva_producto',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_venta', models.IntegerField()),
                ('precio_venta', models.FloatField()),
                ('cliente_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorEmpresa.cliente')),
                ('producto_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorEmpresa.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_compra', models.IntegerField()),
                ('precio_compra', models.FloatField()),
                ('producto_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorEmpresa.producto')),
                ('proveedor_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorEmpresa.proveedor')),
            ],
        ),
    ]
