# Generated by Django 3.2.17 on 2023-02-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorEmpresa', '0004_auto_20230203_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='proveedor_compra',
        ),
    ]
